version: "3.9"

services:
  backend:
    image: python:3.10-slim
    container_name: logwise-backend
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    command: >
      sh -c "
        pip install --no-cache-dir -r requirements.txt &&
        uvicorn main:app --host 0.0.0.0 --port 8000 --reload
      "
    environment:
      - OLLAMA_API=http://host.docker.internal:11434  # Connect to host Ollama

  frontend:
    image: node:18-alpine
    container_name: logwise-frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev"
